### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by tonyday567** [alex404/goal#1]
Hi,

I tried compiling the project with "cabal build all" using ghc-9.4.7 and I ran into:

```
Goal/Geometry/Map/Linear.hs:346:59: error:
    • Couldn't match type ‘L.LinearCompose
                             'L.Full (L.LinearCompose s 'L.Full)’
                     with ‘'L.Full’
      Expected: c # Linear 'L.Full y y
        Actual: c
                # Linear (L.LinearCompose 'L.Full (L.LinearCompose s 'L.Full)) y y
```

and there were a few more that looked similar. Also tried with ghc-9.6.2.

Any hints on how to solve this?

**Comment by alex404** [comment]
Hey, thanks for your interest. There were a few commits I hadn't pushed yet. Try giving it a shot now.

FYI: I'm finishing up a fairly large refactoring of the whole library. I'm hoping to finish up in the next couple of days. There should then be better documentation and more examples.

**Comment by tonyday567** [comment]
Good compile with 9.4.7 and 9.6.2. Thanks!

I'm just poking around at the moment and look forward to seeing the refactor.
